language: java
jdk:
 - oraclejdk8
deploy:
  provider: heroku
  api-key: 
   secure: $HEROKU_API_KEY
  app: cletogadelha-battleship
after_success:
 - mvn clean test jacoco:report coveralls:report  