#DB Config
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/battleship
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
